version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3007:3007"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mensajeria
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: "node src/index.js"

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
